Description: >
    udacity-devops-practice
    This template deploys a VPC with an Internet Gateway attached to it.

Parameters:
    EnvironmentName:
        Description: Environment name that will be prefixed to resources.
        AllowedPattern: "[a-zA-Z0-9-]*"
        Type: String
    
    VpcCIDR:
        Description: The IP range (CIDR notation) for this VPC.
        Type: String
        Default: 10.2.0.0/16

Resources:

    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
    
    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
    
    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC